//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gudlakEntities1 : DbContext
    {
        public gudlakEntities1()
            : base("name=gudlakEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CarsAP> CarsAP { get; set; }
        public virtual DbSet<CarsToDrivers> CarsToDrivers { get; set; }
        public virtual DbSet<CarsType> CarsType { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<DriversAP> DriversAP { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersCarsMileage> OrdersCarsMileage { get; set; }
        public virtual DbSet<OrdersRepeat> OrdersRepeat { get; set; }
        public virtual DbSet<OrdersRoutes> OrdersRoutes { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<RouteTC> RouteTC { get; set; }
        public virtual DbSet<RouteTime> RouteTime { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffType> StaffType { get; set; }
    }
}
