//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrdersCarsMileage = new HashSet<OrdersCarsMileage>();
            this.OrdersRepeat = new HashSet<OrdersRepeat>();
            this.OrdersRoutes = new HashSet<OrdersRoutes>();
        }
    
        public int id { get; set; }
        public int customerid { get; set; }
        public int order_number { get; set; }
        public System.DateTime order_date { get; set; }
        public int statusid { get; set; }
        public Nullable<int> driversid { get; set; }
        public Nullable<int> carsid { get; set; }
        public Nullable<bool> repeat { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersCarsMileage> OrdersCarsMileage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersRepeat> OrdersRepeat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersRoutes> OrdersRoutes { get; set; }
    }
}
