//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersCarsMileage
    {
        public int id { get; set; }
        public int ordersid { get; set; }
        public int carsid { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public Nullable<System.TimeSpan> time_order { get; set; }
        public Nullable<int> start_mileage { get; set; }
        public Nullable<int> end_mileage { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
