//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersRoutes
    {
        public int id { get; set; }
        public int orders_id { get; set; }
        public int route_id { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Route Route { get; set; }
    }
}
