//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GL.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteTime
    {
        public int id { get; set; }
        public int routeid { get; set; }
        public Nullable<System.TimeSpan> time_default_from { get; set; }
        public Nullable<System.TimeSpan> time_default_to { get; set; }
        public Nullable<bool> time_one { get; set; }
        public Nullable<System.TimeSpan> time_one_from { get; set; }
        public Nullable<System.TimeSpan> time_one_to { get; set; }
        public Nullable<bool> time_two { get; set; }
        public Nullable<System.TimeSpan> time_two_from { get; set; }
        public Nullable<System.TimeSpan> time_two_to { get; set; }
        public Nullable<bool> time_three { get; set; }
        public Nullable<System.TimeSpan> time_three_from { get; set; }
        public Nullable<System.TimeSpan> time_three_to { get; set; }
        public Nullable<bool> time_four { get; set; }
        public Nullable<System.TimeSpan> time_four_from { get; set; }
        public Nullable<System.TimeSpan> time_four_to { get; set; }
        public Nullable<bool> time_five { get; set; }
        public Nullable<System.TimeSpan> time_five_from { get; set; }
        public Nullable<System.TimeSpan> time_five_to { get; set; }
        public Nullable<bool> time_six { get; set; }
        public Nullable<System.TimeSpan> time_six_from { get; set; }
        public Nullable<System.TimeSpan> time_six_to { get; set; }
        public Nullable<bool> time_seven { get; set; }
        public Nullable<System.TimeSpan> time_seven_from { get; set; }
        public Nullable<System.TimeSpan> time_seven_to { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
